<center>Calculate SVD from scratch
--

1) **Import numpy and linear algebra libraries**

In [ ]:
import numpy as n
import numpy.linalg as alg

2) **The matrix when decomposed using SVD, decomposes to three elements U,sigma,V**

In [6]:
A = n.array([[1,2],[3,4],[5,6]])
print (f"Original Matrix:: \n{A}")
U,s,V = alg.svd(A)
print("U:: \n",U)
print("Dim :: ",U.shape)
print("Sigma:: \n",s)
print("Dim :: ",s.shape)
print("V:: \n",V)
print("Dim :: ",V.shape)

Original Matrix:: 
[[1 2]
 [3 4]
 [5 6]]
U:: 
 [[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]
Dim ::  (3, 3)
Sigma:: 
 [9.52551809 0.51430058]
Dim ::  (2,)
V:: 
 [[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]
Dim ::  (2, 2)


3) ___Sigma we got is 1xn matrix but we need NxN matrix to recompose it into the original matrix___

In [7]:
Sigma = n.zeros((A.shape[0],A.shape[1]))
Sigma[:A.shape[1],:A.shape[1]] = n.diag(s)
print ("Sigma NxN:: \n",Sigma)


Sigma NxN:: 
 [[9.52551809 0.        ]
 [0.         0.51430058]
 [0.         0.        ]]


4) __Recomposed matrix gives the original matrix__

In [8]:
B = U.dot(Sigma.dot(V))
print ("Recomposing:: \n",B)

Recomposing:: 
 [[1. 2.]
 [3. 4.]
 [5. 6.]]


5) __Calculate PseudoInverse__
* calculate the reciprocals of sigma
* D is a zero matrix to make a NxN diagonal Matrix

**__Calculating PsuedoInverse using the formula__** 
    $$P^{inv} = V^T.D^T.U^T$$


In [10]:
d = 1/s
D=n.zeros(A.shape)
D[:A.shape[1],:A.shape[1]]=n.diag(d)
Pinv = V.T.dot(D.T.dot(U.T))

print ("PsudoInverse:: \n",Pinv)


PsudoInverse:: 
 [[-1.33333333 -0.33333333  0.66666667]
 [ 1.08333333  0.33333333 -0.41666667]]
